# Generated by Django 6.0.2 on 2026-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('REPARACION', 'En Reparación'), ('BAJA', 'Baja'), ('NUEVO', 'Nuevo')], default='NUEVO', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='novedad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
