# Generated by Django 6.0.2 on 2026-05-11 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='inventario.persona'),
        ),
    ]
