# Generated by Django 6.0.2 on 2026-05-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_equipo_usuario_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
