# Generated by Django 6.0.2 on 2026-05-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_equipo_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_registro',
        ),
    ]
