# Generated by Django 6.0.2 on 2026-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_create_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
