# Generated by Django 6.0.2 on 2026-05-18 19:35

import django.db.models.deletion
from django.db import migrations, models

def migrate_personas_to_names(apps, schema_editor):
    Equipo = apps.get_model('inventario', 'Equipo')
    for equipo in Equipo.objects.all():
        if equipo.usuario_asignado_fk:
            equipo.usuario_asignado = equipo.usuario_asignado_fk.nombre
            equipo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_equipo_fecha_asignacion'),
    ]

    operations = [
        # 1. Rename the old ForeignKey field to usuario_asignado_fk
        migrations.RenameField(
            model_name='equipo',
            old_name='usuario_asignado',
            new_name='usuario_asignado_fk',
        ),
        # 2. Add the new CharField field as usuario_asignado
        migrations.AddField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        # 3. Run python code to copy the names from the old ForeignKey to the new CharField
        migrations.RunPython(migrate_personas_to_names),
        # 4. Remove the old ForeignKey field
        migrations.RemoveField(
            model_name='equipo',
            name='usuario_asignado_fk',
        ),
    ]
